ext-beastx:
  type: php-extension
  artifact:
    source:
      type: ghtar
      repo: AhmedSabyrh/my-beast
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  php-extension:
    os:
      - Linux
      - Darwin
      - Windows
    arg-type: enable
